sudo: required
language: cpp

matrix:
  include:
  - os: linux
    sudo: required
    services: docker
    script: sh buildonlinux.sh
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
      keep-history: true
      on:
        branch: master
        tags: true
  - os: osx
    sudo: required
    install:
     - mkdir aws_build && cd aws_build && git clone --depth=1 https://github.com/aws/aws-sdk-cpp.git && cd aws-sdk-cpp && sed -i '' '/ENABLE_TESTING/s/ON/OFF/g' CMakeLists.txt && mkdir build && cd build && cmake -DBUILD_ONLY="s3" -DCMAKE_INSTALL_PREFIX="/opt" .. && make && sudo make install
     - find /opt -name *.pc
     - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/lib/pkgconfig
     - pkg-config --cflags aws-cpp-sdk-s3
     - brew install qt
    script:
     - cd $TRAVIS_BUILD_DIR && git clone --depth=1 https://github.com/journeymidnight/s3util.git && pwd && cd s3util && ls && mkdir build && cd build && /usr/local/opt/qt/bin/qmake ..
     - ls && make
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
      keep-history: true
      on:
        branch: master
        tags: true
