sudo: required
language: cpp

matrix:
  include:
  - os: linux
    sudo: required
    services: docker
    script: sh buildonlinux.sh
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
      keep-history: true
      on:
        branch: master
        tags: true
  - os: osx
    sudo: required
    before_install:
     - brew install qt aws-sdk-cpp pkg-config
     - pkg-config --cflags aws-cpp-sdk-s3
     - find / -name Aws.h
     - cd $TRAVIS_BUILD_DIR && git clone --depth=1 https://github.com/journeymidnight/s3util.git && pwd && cd s3util && ls && mkdir build && cd build && /usr/local/opt/qt/bin/qmake ..
     - ls && make   
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
      keep-history: true
      on:
        branch: master
        tags: true
