sudo: required
language: cpp

matrix:
  include:
  - os: linux
    sudo: required
    services: docker
    script: sh buildonlinux.sh
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
      keep-history: true
      on:
        branch: master
        tags: true
  - os: osx
    sudo: required
    install:
     - mkdir aws_build && cd aws_build && git clone --depth=1 https://github.com/aws/aws-sdk-cpp.git && cd aws-sdk-cpp && sed -i '' '/ENABLE_TESTING/s/ON/OFF/g' CMakeLists.txt && mkdir build && cd build && cmake -DBUILD_ONLY="s3" -DCMAKE_INSTALL_PREFIX="/opt" .. && make && sudo make install
     - find /opt -name *.pc
     - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/opt/lib/pkgconfig
     - pkg-config --cflags aws-cpp-sdk-s3
     - brew install qt
    script:
     - cd $TRAVIS_BUILD_DIR && git clone --depth=1 https://github.com/journeymidnight/s3util.git && pwd && cd s3util && ls && mkdir build && cd build && /usr/local/opt/qt/bin/qmake ..
     - ls && make
     - otool -L s3util
     - find /usr/* -name libaws-cpp-sdk-s3.dylib
     - mkdir libs \
&& cp /usr/lib/x86_64-linux-gnu/libaws-cpp-sdk-s3.so libs/ \
&& cp /usr/lib/x86_64-linux-gnu/libaws-cpp-sdk-core.so  libs/ \
&& cp /opt/qt59/lib/libQt5Core.so.5 libs/ \
&& cp /opt/qt59/lib/libQt5Concurrent.so libs/ \
&& cp /usr/lib/x86_64-linux-gnu/libcrypto.so* libs/ \
&& cp /usr/lib/x86_64-linux-gnu/libicui18n.so* libs/ \
&& cp /usr/lib/x86_64-linux-gnu/libicuuc.so* libs/ \
&& cp /usr/lib/x86_64-linux-gnu/libicudata.so* libs/ \
&& tar czvf s3util_binary.tar.gz s3util libs \
&& mv s3util_binary.tar.gz /work
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
      keep-history: true
      on:
        branch: master
        tags: true
