sudo: required
language: cpp

services:
  - docker

os:
 - linux
 - osx

before_install:
 - echo hehehehe

script:
 - echo 11111
 - echo 22222

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
    tags: true
