sudo: required
language: cpp

matrix:
  include:
  - os: linux
    services: docker
    script: echo 1111
  - os: mac
    script: echo 2222

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
    tags: true
